# Generated by Django 3.2.5 on 2021-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('cantidad', models.IntegerField()),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
