# Generated by Django 3.2.5 on 2021-09-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ventaservicio',
            name='servicio',
            field=models.CharField(max_length=64),
        ),
    ]
