# Generated by Django 3.2.5 on 2021-09-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210906_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='fecha',
        ),
    ]
