# Generated by Django 3.2.5 on 2021-09-06 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ventaproducto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='fecha_venta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
