# Generated by Django 3.2.5 on 2021-09-06 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ventaproducto_fecha_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproducto',
            name='id',
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='fecha_venta',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
