# Generated by Django 3.2.5 on 2021-09-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210903_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ganancia', models.FloatField(default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='VentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ganancia', models.FloatField(default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('servicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
