# Generated by Django 3.2.5 on 2021-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210906_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
