# Generated by Django 3.2.5 on 2021-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_servicio_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_venta',
            field=models.FloatField(),
        ),
    ]
