# Generated by Django 3.2.5 on 2021-09-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_servicio_precio_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaservicio',
            old_name='fecha',
            new_name='fecha_venta',
        ),
    ]
